name: "\U0001FAB2 Bug report"
description: "Bug in GridKit™ code"
title: "Bug: "
labels: [bug]
body:
  - type: textarea
    id: reproduce
    attributes:
      label: "Description how to reproduce the bug"
      description: "Please provide launch command and the output when you encounter bug."
      value: |
        ```console
        $ ./gridkit_app
        (...)
        ```
        If the error output is long, attach a file or write it in a block that can be closed:
        <details>
        
        ```
        $ ./gridkit_app
        (...)
        ```
        </details>
    validations:
      required: true

  - type: markdown
    id: gridkit-version
    attributes:
      label: "GridKit Version"
      description: |
        Please include the version of GridKit™ which demonstrates the problem.
        If building from source on a non-tagged version, please include the commit hash.
    validations:
      required: true

  - type: textarea
    id: system-info
    attributes:
      label: "System and environment details"
      description: |
        Please include details about your system, such as:
        - Operating system  
        - Compilers  
        - Hardware backends (CUDA, HIP)  
        - Dependencies and package versions  
    validations:
      required: true

  - type: textarea
    id: additional_information
    attributes:
      label: "Additional information"
      description: "Upload additional debugging information, such as backtrace."
