name: "\U0001F4A5 Build error"
description: "Unable to build GridKit"
title: "Build issue: "
labels: [cmake]
body:
  - type: textarea
    id: reproduce
    attributes:
      label: "Build error message(s)"
      description: "Instructions how to reproduce build failure and the error output."
      value: |
        ```console
        $ make
        ...
        ```
    validations:
      required: true

  - type: textarea
    id: information
    attributes:
      label: "System and environment details"
      description: |
        Please include details about your system, such as:
        - Operating system  
        - Compilers  
        - Hardware backends (CUDA, HIP)  
        - Dependencies and package versions  
    validations:
      required: true

  - type: textarea
    id: additional_information
    attributes:
      label: "Additional information"
      description: "Upload build logs or provide any additional context about the issue."
