name: "\U0001F4A5 Build error"
description: "Unable to build ReSolve"
title: "Build issue: "
labels: [build-error]
body:
  - type: textarea
    id: reproduce
    attributes:
      label: "CMake error message(s)"
      description: "Fill in the console output when you try to build."
      value: |
        ```console
        $ make
        ...
        ```
    validations:
      required: true

  - type: textarea
    id: information
    attributes:
      label: "System and environment details"
      description: |
        Please include details about your system, such as:
        - Operating system  
        - Compilers  
        - Hardware backends (CUDA, HIP)  
        - Dependencies and package versions  
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        If you have relevant configuration details (e.g., custom `packages.yaml` or `modules.yaml`), you can add them below.

  - type: textarea
    id: additional_information
    attributes:
      label: "Additional information"
      description: "Upload build logs or provide any additional context about the issue."
