name: "\U0001F38A Feature request"
description: Suggest adding a feature that is not yet in ReSolve
labels: [feature]
body:
  # CHECKBOX:
  - type: checkboxes
    id: checkboxes
    attributes:
      label: What kinds of M&Ms do you like?
      description: You may select more than one.
      options:
        - label: Green
        - label: Orange
        - label: Red
        - label: Yellow
    validations:
      required: false

