name: "\U0001F38A Feature request"
description: Suggest adding a feature that is not yet in ReSolve
labels: [feature]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Please add a concise summary of your suggestion here.
    validations:
      required: true
  # CHECKBOX:
  - type: checkboxes
    id: checkboxes
    attributes:
      label: What kinds of M&Ms do you like?
      description: You may select more than one.
      options:
        - label: Green
        - label: Orange
        - label: Red
        - label: Yellow
    validations:
      required: false

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Is your feature request related to a problem? Please describe it!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the solution you'd like and the alternatives you have considered.
  - type: textarea
    id: additional_information
    attributes:
      label: Additional information
      description: Add any other context about the feature request here.
