name: "\U0001F4A5 Tests error"
description: "Some Re::Solve tests are failing"
title: "Testing issue: "
labels: [testing]
body:
  - type: textarea
    id: reproduce
    attributes:
      label: "Failed test outputs or steps to reproduce the failure(s)"
      description: |
        Fill in the failing test output, errors,  
        or steps to reproduce the failure(s).
      value: |
        ```console
        $ ctest -VV --rerun-failed
        ...
        ```
    validations:
      required: true

  - type: textarea
    id: information
    attributes:
      label: "System and environment details"
      description: |
        Please include details about your system, such as:
        - Operating system  
        - Compilers  
        - Hardware backends (CUDA, HIP)  
        - Dependencies and package versions  
    validations:
      required: true

  - type: textarea
    id: additional_information
    attributes:
      label: "Additional information"
      description: "Upload test logs or provide any additional context about the issue."
